name: Check

on: 
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Link Check
        run: npm run lint
      - name: Run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Test Check
        env:
          PORT: ${{ secrets.PORT }}
        run: npm run test